// Vital Checkup report PDF — vitals + normal/abnormal flags + advice.
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { VitalsFlags } from "@/lib/vitals-thresholds";

const s = StyleSheet.create({
  page: { padding: 36, fontSize: 11, fontFamily: "Helvetica", color: "#0E2A33" },
  brand: { fontSize: 18, color: "#0F4C5C", fontFamily: "Helvetica-Bold" },
  header: { borderBottom: "2 solid #0F4C5C", paddingBottom: 8, marginBottom: 12, flexDirection: "row", justifyContent: "space-between" },
  muted: { color: "#5C6B73", fontSize: 9 },
  row: { flexDirection: "row", borderBottom: "0.5 solid #e5e7eb", paddingVertical: 5 },
  c1: { width: "50%" }, c2: { width: "30%" }, c3: { width: "20%" },
  label: { color: "#5C6B73", fontSize: 8, textTransform: "uppercase" },
  banner: { padding: 8, marginTop: 12, borderRadius: 4 }
});

const FLAG_TEXT: Record<string, string> = { normal: "Normal", low: "Low", high: "High", critical: "Critical" };

export type VitalsReportData = {
  patientName: string;
  date: string;
  rows: { label: string; value: string; flag?: string }[];
  summary: string;
  escalate: boolean;
  providerNotes?: string | null;
};

export function VitalsReportDoc(d: VitalsReportData) {
  return (
    <Document>
      <Page size="A4" style={s.page}>
        <View style={s.header}>
          <Text style={s.brand}>HANUone</Text>
          <Text style={s.muted}>Vital Checkup · {d.date}</Text>
        </View>

        <Text style={{ fontFamily: "Helvetica-Bold" }}>{d.patientName}</Text>

        <View style={[s.row, { marginTop: 12 }]}>
          <Text style={[s.c1, s.label]}>Vital</Text>
          <Text style={[s.c2, s.label]}>Value</Text>
          <Text style={[s.c3, s.label]}>Status</Text>
        </View>
        {d.rows.map((r, i) => (
          <View key={i} style={s.row}>
            <Text style={s.c1}>{r.label}</Text>
            <Text style={s.c2}>{r.value}</Text>
            <Text style={[s.c3, { color: r.flag && r.flag !== "normal" ? "#b91c1c" : "#15803d" }]}>
              {r.flag ? FLAG_TEXT[r.flag] ?? r.flag : "-"}
            </Text>
          </View>
        ))}

        <View style={[s.banner, { backgroundColor: d.escalate ? "#fee2e2" : "#ecfdf5" }]}>
          <Text style={{ color: d.escalate ? "#991b1b" : "#065f46", fontSize: 10 }}>{d.summary}</Text>
        </View>

        {d.providerNotes ? (
          <View style={{ marginTop: 12 }}>
            <Text style={s.label}>Provider notes</Text>
            <Text>{d.providerNotes}</Text>
          </View>
        ) : null}

        <Text style={[s.muted, { marginTop: 18 }]}>
          This report summarises measured vitals and is not a medical diagnosis. Please consult a
          doctor for interpretation. Generated by Hanuone Vital Checkup.
        </Text>
      </Page>
    </Document>
  );
}

export function flagFor(flags: VitalsFlags, key: string): string | undefined {
  return (flags as Record<string, string>)[key];
}
